app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
]

app/pages/urls.py
from django.urls import path
from .views import IndexView, DetailView, CategoryView, TagView


app_name = "pages"

urlpatterns = [
    # path('', views.index, name='index'),
    path("", IndexView.as_view(), name="index"),
    path('category/<str:category>/', CategoryView.as_view(), name='category'),
    path('tag/<str:tag>/', TagView.as_view(), name='tag'),
    path("detail/<int:pk>/", DetailView.as_view(), name="detail"),
]

app/pages/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('category name', max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('tag name', max_length=50)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField('title', max_length=100)
    text = models.TextField('text')
    category = models.ForeignKey(Category, verbose_name='category', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, verbose_name='tag')
    relation = models.ManyToManyField('self', verbose_name='relation', blank=True, null=True)
    created_at = models.DateTimeField('created date', auto_now_add=True)
    updated_at = models.DateTimeField('updated date', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

app/pages/views.py
# from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView
from .models import Blog, Category, Tag


# Create your views here.
# class HomePageView(TemplateView):
#     template_name = "home.html"

# def index(request):
#     blogs = Blog.objects.order_by('-id')
#     return render(request, 'index.html', {'blogs': blogs})


# def detail(request, blog_id):
#     blog_tex = get_object_or_404(Blog, pk=blog_id)
#     return render(request, 'detail.html', {'blog': blog_tex})

class IndexView(ListView):
    model = Blog
    context_object_name = "blog_list"
    template_name = 'pages/index.html'

    def get_queryset(self):
        queryset = Blog.objects.order_by('-id')
        return queryset


class CategoryView(ListView):
    """カテゴリー一覧"""
    model = Blog
    context_object_name = "blog_list"
    template_name = 'pages/index.html'

    def get_queryset(self):
        """カテゴリーで絞り込み"""
        category = Category.objects.get(name=self.kwargs['category'])
        queryset = Blog.objects.order_by('-id').filter(category=category)
        return queryset


    def get_context_data(self, **kwargs):
        """テンプレートに渡す辞書の作成"""
        context = super().get_context_data(**kwargs)
        context['category_key'] = self.kwargs['category']
        return context


class TagView(ListView):
    """タグ一覧"""
    model = Blog
    context_object_name = "blog_list"
    template_name = 'pages/index.html'

    def get_queryset(self):
        """タグで絞り込み"""
        tag = Tag.objects.get(name=self.kwargs['tag'])
        queryset = Blog.objects.order_by('-id').filter(tag=tag)
        return queryset


    def get_context_data(self, **kwargs):
        """テンプレートに渡す辞書の作成"""
        context = super().get_context_data(**kwargs)
        context['tag_key'] = self.kwargs['tag']
        return context


class DetailView(DetailView):
    model = Blog
    context_object_name = "blog"
    template_name = 'pages/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = Blog.objects.get(pk=self.kwargs['pk'])
        return context

app/templates/home.html
{% block title %}Home{% endblock title %}

{% block content %}
  <h1>This is our home page.</h1>
{% endblock content %}

app/templates/pages/base.html
<!-- templates/pages/base.html -->

<!doctype html>
<html>
  <head>

    <title>Blog</title>

  </head>
<body>

     <h1>Blog</h1>
     {% block content %}
     {% endblock %}

</body>
</html>

app/templates/pages/detail.html
<!-- templates/blog/detail.html -->

{% extends 'pages/base.html' %}

{% block content %}

    <h1>{{ blog.title }}</h1>
    <p>{{ blog.updated_at }}</p>
    {{ blog.text | safe | linebreaksbr }}<hr />
    </br>

    <a href="{% url 'pages:index' %}">トップページに戻る</a>

    <!-- 関連記事の呼び出し -->
    <h1>関連項目</h1>
    {% if blog.relation.all %}
        {% for blog in blog.relation.all %}
            <a href='{% url 'pages:detail' blog.pk %}'>
                <li>{{ blog }}</li>
            </a>
        {% endfor %}
    {% else %}
        <h2>ありません<h2>
    {% endif %}

{% endblock %}

app/templates/pages/index.html
<!-- templates/pages/index.html -->

{% extends 'pages/base.html' %}

{% block content %}

    <a href='{% url 'pages:index' %}'><p>トップ</p></a>

    <div>
        <h4>カテゴリー</h4>
        {% for category in category_list %}
                 <a href="{% url 'pages:category' category %}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <!-- タグ用 -->
    <div style='clear: both;'>
        <h4>タグ</h4>
        {% for tag in tag_list %}
            <a href='{% url 'pages:tag' tag %}'>{{ tag.name }}</a>
        {% endfor %}
    </div>

    <h1>一覧</h1><br>
    <!-- contextの辞書から取得 -->
    {% if category_key %}
        <h3>カテゴリー：{{ category_key }}</h3>
    {% elif tag_key %}
        <h3>タグ: {{ tag_key }}</h3>
    {% endif %}

    {% for blog in blog_list %}
        <ul>
            <li>
               {{ blog.created_at }}
               {{ blog.title }}
               <a href="{% url 'pages:detail' blog.pk %}">詳細</a>
           </li>
       </ul>
    {% endfor %}

    hello world

{% endblock %}